previewsEnabled: true
services:
- type: web
  name: real-reddit-client
  env: static
  repo: https://github.com/bennbenben/real-reddit.git
  branch: main
  plan: free
  region: singapore
  buildCommand: cd client && ./render-build.sh
  staticPublishPath: ./client/build/
  buildFilter:
    paths:
    - client/**
- type: web
  name: real-reddit-server
  env: node
  repo: https://github.com/bennbenben/real-reddit.git
  branch: main
  plan: free
  region: singapore
  buildCommand: cd server && ./render-build.sh
  startCommand: cd server && ./render-start.sh
  buildFilter:
    paths:
    - server/**
  