previewsEnabled: true
services:
- type: web
  name: real-reddit-server
  env: node
  branch: main
  buildCommand: cd server && ./render-build.sh
  startCommand: cd server && ./render-start.sh
  buildFilter:
    paths:
    - server/**
- type: web
  name: real-reddit-client
  env: static
  branch: main
  buildCommand: cd client && ./render-build.sh
  staticPublishPath: ./client/build/
  buildFilter:
    paths:
    - client/**